version: 2.1

jobs:
  build-lint-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1
          paths:
            - "venv"

      - run:
            name: run linter
            command: |
              . venv/bin/activate
              flake8
              # mkdir -p test-results/flake8
              # flake8 . --output-file=flake8.txt test-results/flake8/
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir -p test-results/pytest
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results


workflows:
  main-workflow:
    jobs:
      - build-lint-and-test