version: 2.1

jobs:
  build-lint-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: virtual env
          command: env/scripts/activate
      - run:
            name: install dependencies
            command: pip install -r requirements.txt
      - run:
            name: run linter
            command: |
              mkdir -p test-results/flake8
              flake8 . --output-file=test-results/flake8/flake8.txt
      - run:
          name: run tests
          command: |
            mkdir -p test-results/pytest
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results


workflows:
  main-workflow:
    jobs:
      - build-lint-and-test